rails-enterprise-sso/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'sso', to: 'logins#index', as: :login
  post 'sso', to: 'sorcery#oauth'

  delete 'logout' => 'logins#destroy', as: :logout

  resource :oauth do
    get :callback, to: 'sorcery#callback', on: :collection
  end

  get 'profile', to: 'profiles#index', as: :profile

  get '/setup/sso', to: 'ssos#index', as: :setup_sso
  post '/setup/sso', to: 'ssos#save_connection', as: :save_connection

  # OmniAuth
  get 'auth/boxyhqsso/callback', to: 'omniauth#callback'
  get 'omniauth/profile', to: 'omniauth_profiles#show', as: :omniauth_profile
  delete 'omniauth/logout' => 'omniauth#logout', as: :omniauth_logout
end

rails-enterprise-sso/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-enterprise-sso/app/models/authentication.rb
# app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

rails-enterprise-sso/app/models/user.rb
# app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  authenticates_with_sorcery!
end

rails-enterprise-sso/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_action :require_login, except: [:not_authenticated]

  def omniauth_user
    @user = session[:userinfo]
  end

  helper_method :omniauth_user

  protected

  def not_authenticated # only for sorcery
    redirect_to login_path, alert: '⚠️ Please login using sorcery first.'
  end
end

rails-enterprise-sso/app/controllers/concerns/omniauth_secured.rb
module OmniauthSecured
    extend ActiveSupport::Concern
  
    included do
      before_action :logged_in_using_omniauth?
    end
  
    def logged_in_using_omniauth?
      redirect_to login_path, notice: "⚠️ Please login using omniauth" unless session[:userinfo].present?
    end
end

rails-enterprise-sso/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

rails-enterprise-sso/app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  skip_before_action :require_login

  def index; end

  def destroy
    logout
    redirect_to(root_path, notice: 'Logged out!')
  end
end

rails-enterprise-sso/app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  skip_before_action :require_login, raise: false

  def index; end

  def oauth
    # tenant = params[:teamId]
    login_at('boxyhqsaml', state: SecureRandom.hex(16))
  end

  # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
  def callback
    provider = 'boxyhqsaml'
    if @user = login_from(provider)
      redirect_to profile_path, notice: "Logged in from #{provider.titleize}!"
    else
      begin
        @user = create_from(provider)

        # @user.activate!
        reset_session # protect from session fixation attack
        auto_login(@user)
        redirect_to profile_path, notice: "Logged in from #{provider.titleize}!"
      rescue
        redirect_to root_path, alert: "Failed to login from #{provider.titleize}!"
      end
    end
  rescue ::OAuth2::Error => e
    Rails.logger.error e
    Rails.logger.error e.code
    Rails.logger.error e.description
    Rails.logger.error e.message
    Rails.logger.error e.backtrace
  end
end

rails-enterprise-sso/app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController
  skip_before_action :require_login, raise: false

    def callback
      user_info = request.env['omniauth.auth']
      session[:userinfo] = user_info['extra']['raw_info']
      redirect_to omniauth_profile_path,  notice: "Logged in using omniauth!"
    end

    def logout
      reset_session
      redirect_to root_path,  notice: "Logged out from Omniauth!"
    end
  end

rails-enterprise-sso/app/controllers/omniauth_profiles_controller.rb
class OmniauthProfilesController < ApplicationController
    skip_before_action :require_login, raise: false
    include OmniauthSecured
  
    def show
      @user = session[:userinfo]
    end
  end
  

rails-enterprise-sso/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index; end
end

rails-enterprise-sso/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, raise: false

    def callback
      user_info = request.env['omniauth.auth']
      session[:userinfo] = user_info['extra']['raw_info']
      redirect_to omniauth_profile_path,  notice: "Logged in using omniauth!"
    end
  end

rails-enterprise-sso/app/controllers/sorcery_controller.rb
class SorceryController < ApplicationController
  skip_before_action :require_login, raise: false

  def oauth
    login_at('boxyhqsso', state: SecureRandom.hex(16))
  end

  # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
  def callback
    provider = 'boxyhqsso'
    if @user = login_from(provider)
      redirect_to profile_path, notice: "Logged in from #{provider.titleize}!"
    else
      begin
        @user = create_from(provider)

        # @user.activate!
        reset_session # protect from session fixation attack
        auto_login(@user)
        redirect_to profile_path, notice: "Logged in from #{provider.titleize}!"
      rescue StandardError => e
        redirect_to root_path, alert: "Failed to login from #{provider.titleize}! :: #{e.inspect}"
      end
    end
  rescue ::OAuth2::Error => e
    Rails.logger.error e
    Rails.logger.error e.code
    Rails.logger.error e.description
    Rails.logger.error e.message
    Rails.logger.error e.backtrace
  end
end

rails-enterprise-sso/app/controllers/ssos_controller.rb
class SsosController <  ApplicationController
    skip_before_action :require_login

    TENANT='boxyhq.com'
    PRODUCT='saml-demo.boxyhq.com'

    def initialize
        super
        @jackson_client = JacksonApi::V1::Client.new
    end

    def index
        @connections = @jackson_client.retrieve_sso_connections(tenant: TENANT,product: PRODUCT)
    end

    def save_connection
        connection_parameters = {
            "tenant" => TENANT,
            "product" => PRODUCT,
            "redirectUrl" => ENV['APP_URL'],
            "defaultRedirectUrl" => ENV['APP_URL'] + '/oauth/callback',
            "rawMetadata" => params[:metadata]
        }
        
        @jackson_client.create_sso_connection(connection_parameters)

        redirect_to setup_sso_path
    end
end

rails-enterprise-sso/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-enterprise-sso/app/helpers/sso_helper.rb
module SsoHelper
end

rails-enterprise-sso/app/views/home/index.html.erb
<div class="max-w-7xl mx-auto relative top-10">
  <div class="space-y-3 px-3 py-3 border border-gray-200">
    <h1 class="text-2xl">Enterprise SSO + Ruby on Rails Framework Example</h1>
    <p>
      This is an example web app that demonstrate how to use Enterprise SSO with
      Rails Framework.
    </p>
    <ul class="flex flex-row space-x-6">
      <li>
        <a
          class="underline underline-offset-2"
          target="_blank"
          rel="noreferrer"
          href="https://boxyhq.com/docs/jackson/overview"
        >
          Documentation
        </a>
      </li>
      <li>
        <a
          class="underline underline-offset-2"
          target="_blank"
          rel="noreferrer"
          href="https://github.com/boxyhq/jackson"
        >
          Github
        </a>
      </li>
      <li>
        <a
          class="underline underline-offset-2"
          target="_blank"
          rel="noreferrer"
          href="https://hub.docker.com/r/boxyhq/jackson"
        >
          Docker Hub
        </a>
      </li>
    </ul>
  </div>
</div>

rails-enterprise-sso/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsEnterpriseSso</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'toast', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "toast", media: "all", "data-turbo-track" => "reload"  %>
  </head>

  <body>
  <header>
      <nav class="border-gray-200 px-4 py-4 shadow leading-6">
        <div class="max-w-7xl mx-auto">
          <ul class="flex gap-4">
            <li>
              <%=  link_to 'Home', root_path , class: 'font-normal text-gray-900'%>
            </li>
            <li>
               <%=  link_to 'Setup SSO', setup_sso_path , class: 'font-normal text-gray-900'%>
            </li>
            <% if current_user %>
            <li>
             <%=  link_to 'Profile', profile_path , class: 'font-normal text-gray-900'%>
            </li>
            <li class="ml-auto">
              <%=  link_to 'Log out', logout_path, method: :delete %>
            </li>
            <%# omniauth %>
            <% elsif omniauth_user %>
            <li>
             <%=  link_to 'Profile', omniauth_profile_path , class: 'font-normal text-gray-900'%>
            </li>
            <li class="ml-auto">
              <%=  link_to 'Log out', omniauth_logout_path, method: :delete %>
            </li>            
            <% else %>
             <li>
             <%=  link_to 'Login', login_path , class: 'font-normal text-gray-900', data: { turbolinks: "false" }%>
            </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <main class="h-[calc(100vh-56px)]">
      <%= render partial: 'shared/toast'  %>
      <%= yield %>
    </main>
  </body>
</html>

rails-enterprise-sso/app/views/logins/index.html.erb
<div class="max-w-7xl mx-auto h-full">
  <div class="flex flex-col space-y-5 justify-center h-full">
    <h2 class="text-center text-3xl">Log in to App</h2>
    <div class="max-w-md mx-auto w-full px-3 md:px-0">
      <div class="py-5 px-5 border-gray-200 border bg-white rounded">
      <%= form_with url: "/sso", class: "space-y-3" do |form| %>
        <%= form.label :tenant, "Tenant", class: "block text-sm" %>
        <%= form.text_field :tenant, class: "appearance-none text-sm block w-full border border-gray-300 rounded placeholder-gray-400 focus:outline-none focus:ring-indigo-500", required: true %>
        <%= form.hidden_field :product, value: "saml-demo.boxyhq.com"  %>
        <%= form.submit "Login with Enterprise SSO (Sorcery)", name: nil, class: "px-4 py-2 w-full border border-transparent rounded text-sm font-medium text-white bg-indigo-600 focus:outline-none" %>
        <%= form.submit "Login with Enterprise SSO (OmniAuth)", name: nil, class: "px-4 py-2 w-full border border-transparent rounded text-sm font-medium text-white bg-indigo-600 focus:outline-none", formaction: "/auth/boxyhqsso"%>
      <% end %>
      </div>
    </div>
  </div>
</div>

rails-enterprise-sso/app/views/profiles/index.html.erb
    <div class="max-w-7xl mx-auto relative top-10">
      <div class="max-w-[50%]">
        <div class="py-5 px-5 border-gray-200 border bg-white rounded">
          <ul class="flex flex-col space-y-3">
            <li class="flex flex-col">
              <span class="font-normal">User ID</span>
              <span class="text-gray-500"><%= current_user.id %></span>
            </li>
            <li class="flex flex-col">
              <span class="font-normal">Email</span>
              <span class="text-gray-500"><%= current_user.email %></span>
            </li>
            <li class="flex flex-col">
              <span class="font-normal">First Name</span>
              <span class="text-gray-500"><%= current_user.firstName %></span>
            </li>
            <li class="flex flex-col">
              <span class="font-normal">Last Name</span>
              <span class="text-gray-500"><%= current_user.lastName %></span>
            </li>
          </ul>
        </div>
      </div>
    </div>

rails-enterprise-sso/app/views/shared/_toast.html.erb
<% flash.each do |type, msg| %>
    <div class="toast">
        <%= msg %>
    </div>
    <script>showToast()</script>
<% end %>

rails-enterprise-sso/app/views/sso/index.html.erb
<div class="max-w-7xl mx-auto h-screen">
  <div class="flex flex-col space-y-5 justify-center h-full">
    <h2 class="text-center text-3xl">Log in to App</h2>
    <div class="max-w-md mx-auto w-full px-3 md:px-0">
      <div class="py-5 px-5 border-gray-200 border bg-white rounded">
        <form class="space-y-3" method="POST" action="">
          <label htmlFor="teamId" class="block text-sm">Team ID</label>
          <input
            type="text"
            name="teamId"
            id="teamId"
            placeholder="boxyhq"
            class="appearance-none text-sm block w-full border border-gray-300 rounded placeholder-gray-400 focus:outline-none focus:ring-indigo-500"
            required
          />
          <button
            type="submit"
            class="px-4 py-2 w-full border border-transparent rounded text-sm font-medium text-white bg-indigo-600 focus:outline-none"
          >
            Login with Enterprise SSO
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

rails-enterprise-sso/app/views/ssos/index.html.erb
<div class="max-w-7xl mx-auto relative top-10">
    <div class="max-w-[50%]">
        <div class="mb-5">
           <% if @connections.length == 0 %>
            <span class="bg-red-100 text-red-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded">SAML SSO Not
                Enabled</span>
            <% else %>
            <span class="bg-green-100 text-green-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded">SAML SSO
                Enabled</span>
            <% end %>
        </div>
        <div class="py-5 px-5 border-gray-200 border bg-white rounded">
            <form class="space-y-3" method="POST" action="/setup/sso">
                <label htmlFor="metadata" class="block text-sm">XML Metadata</label>
                <textarea name="metadata" id="metadata" placeholder="Paste the XML Metadata"
                    class="appearance-none text-sm block w-full border border-gray-300 rounded placeholder-gray-400 focus:outline-none focus:ring-indigo-500"
                    required rows="10"></textarea>
                <button type="submit"
                    class="px-4 py-2 w-full border border-transparent rounded text-sm font-medium text-white bg-indigo-600 focus:outline-none">
                    Save Changes
                </button>
            </form>
        </div>
        <p class="mt-5 text-sm text-gray-600">
            You can use
            <a href="https://mocksaml.com/" class="font-medium underline underline-offset-2">
                Mock SAML
            </a>
            a free SAML 2.0 Identity Provider to test the SAML SSO integration.
        </p>
    </div>
</div>